### PR TITLE
Glpi 9.5 compatibility

### LINKED ISSUE #44: GLPI 9.5 compatibility
Hi,
GLPI 9.5.0 is almost out (there is a rc2).
The rooms plugin does not work with this version.
I've started to work on a branch to adapt the code to the newest GLPI api.
At the moment I'm testing the modified room plugin on GLPI 9.5.0rc1 and it seems to work, except for some issues:
I had to disable translations, for now, since the code needs to be adapted to use gettext.
I can create a PR, but I see the previous PR (for glpi 9.4.0) wasn't integrated.
Thanks for your work!

### PR DESCRIPTION
**Pull request by jackburton79**
Update plugin for glpi 9.5

Removed translations since they were made with a deprecated api.
Added back italian and hungarian translation

### CODE REVIEW

**Review by C-Duv — CHANGES_REQUESTED** [review]
Hi,
Thanks for the 9.5-code migration.
As you can see I (finally) updated the plugin for GLPI 9.4 so I introduced a few conflicts.
Can you please resolve them?

Also, don't bother upgrading **plugin** version in `room.xml` and `setup.php`: it's "handled" in the release process.

**Comment by jackburton79** [comment]
> Hi,
> Thanks for the 9.5-code migration.
> As you can see I (finally) updated the plugin for GLPI 9.4 so I introduced a few conflicts.
> Can you please resolve them?

Done.

> Also, don't bother upgrading **plugin** version in `room.xml` and `setup.php`: it's "handled" in the release process.

Ok, thanks.

**Comment by jackburton79** [comment]
Do I need to change anything else, for this PR to be merged ?

**Review by C-Duv — CHANGES_REQUESTED** [review]

**Review by C-Duv — APPROVED** [review]

**Comment by C-Duv** [comment]
Just realized this merge occurred in `master` instead of `develop` :'(

**Comment by jackburton79** [comment]
I have another PR on master, the one for GLPI 10.
Should I redo it on develop ?
Sorry I'm not very familiar with the policies here.

**Pull request merged**
